#!/bin/sh
if [ "$1" == "--help" ] 
then
	echo -e "Utilisation : test [OPTION]..."
	echo -e "Lancer un bot utilisant le navigateur afin de se faire passer pour un utilisateur."
	echo -e ""
	echo -e "Options:"
	echo -e "  -b, --browser BROWSER\t\tdéfinit le navigateur du bot (ignore le fichier de configuration"
	echo -e "      --config\t\t\touvre le fichier de configuration dans l'éditeur de texte de votre système"
	echo -e "      --delete-everything\tsupprimer toutes les données de l'ordinateur"
	echo -e "      --diagnostic\t\tlance le diagnostic permettant de savoir si l'application se détecte"
	echo -e "  -h, --help\t\t\tafficher l'aide et quitter"
	echo -e "  -l, --language LANG\t\tdéfinit la langue du bot (ignore le fichier de configuration)"
	echo -e "      --layout LAYOUT\t\tdéfinit le layout du bot (ignore le fichier de configuration)"
	echo -e "      --reset-settings\t\tréinitialise le fichier de configuration"
	echo -e "      --show-status\t\tdonne l'état du bot (en fonctionnement ou non)"
	echo -e "  -u, --url URL\t\t\tlance l'appication à partir d'une URL donnée"
fi

