#!/bin/sh
if [ "$1" = "--help" ]
then
	echo  "Utilisation : test [OPTION]..."
	echo  "Lancer un bot utilisant le navigateur afin de se faire passer pour un utilisateur."
	echo  ""
	echo  "Options:"
	echo  "  -b, --browser BROWSER\t\tdéfinit le navigateur du bot (ignore le fichier de configuration)"
	echo  "      --config\t\t\touvre le fichier de configuration dans l'éditeur de texte de votre système"
	echo  "      --delete-everything\tsupprimer toutes les données de l'ordinateur"
	echo  "      --diagnostic\t\tlance le diagnostic permettant de savoir si l'application se détecte"
	echo  "  -h, --help\t\t\tafficher l'aide et quitter"
	echo  "  -l, --language LANG\t\tdéfinit la langue du bot (ignore le fichier de configuration)"
	echo  "      --layout LAYOUT\t\tdéfinit le layout du bot (ignore le fichier de configuration)"
	echo  "      --reset-settings\t\tréinitialise le fichier de configuration"
	echo  "      --show-status\t\tdonne l'état du bot (en fonctionnement ou non)"
	echo  "      --stop\t\t\tarrête le bot"
	echo  "  -u, --url URL\t\t\tlance l'appication à partir d'une URL donnée"
	echo  "  -v, --verbose NUM\t\tdéfinit le niveau de retour d'information à NUM (défaut : 0) A N'UTILISER QUE POUR LE DEBUG"
	echo  "      --visible BOOL\t\tdéfinit la visibilité du navigateur"
fi

if [ "$1" = "--verbose" ]
then
	echo "paramètres choisis : langue : fr_FR, layout : fr, browser : firefox, visibilité : visible"
	echo "lancement du navigateur OK"
	echo "accès à la page \"duckduckgo.com\""
	echo "analyse de la page..."
	echo "1 champ(s) de texte"
	echo "1 bouton(s)"
	echo "3 lien(s)"
	echo "sélection du champ de text id=\"search_form_input_homepage\""
	echo "texte entré : \"test\""
	echo "appui du bouton id=\"search_button_homepage\""
	echo "accès à la page \"https://duckduckgo.com/?q=test\""
	echo "accès à la page \"https://duckduckgo.com/?q=test&ia=meanings\""
	echo "analyse de la page..."
	echo "1 champ(s) de texte"
	echo "1 boutton(s)"
	echo "194 lien(s)"
fi