#!/bin/bash

printf "setup python modules..."

pyMod=$(pip list --format columns | grep Uinput)
pyMain=$(find /usr/local/lib/python2.7/ | grep nina.py)
gd=$(find /usr/local/bin/ -name geckodriver)

if [ -z "$pyMod" ]; then
  cd src/ctrl_keyboard
  sudo python setup.py install
  cd -
fi

if [ -z "$pyMain" ]; then
  sudo cp src/navigation/nina.py /usr/local/lib/python2.7/
fi

if [ -z "$gd" ]; then
  wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz && tar -xvf geckodriver-v0.11.1-linux64.tar.gz && rm geckodriver-v0.11.1-linux64.tar.gz && mv geckodriver /usr/local/bin/
fi

printf " done.\n"
