#!/bin/bash
printf "setup python modules..."

gd=$(find /usr/local/bin/ -name geckodriver)

cd src/ctrl_keyboard
sudo python setup.py install
cd -

if cat /etc/*release | grep ^NAME | grep Debian ; then
  sudo cp src/navigation/nina.py /usr/local/lib/python2.7/dist-packages/
elif cat /etc/*release | grep ^NAME | grep Ubuntu ; then
  sudo cp src/navigation/nina.py /usr/local/lib/python2.7/dist-packages/
else
  sudo cp src/navigation/nina.py /usr/local/lib/python2.7/site-packages/
fi

if [ -z "$gd" ]; then
  wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz && tar -xvf geckodriver-v0.11.1-linux64.tar.gz && rm geckodriver-v0.11.1-linux64.tar.gz && mv geckodriver /usr/local/bin/
fi

printf " done.\n"
