# -*- coding: utf-8 -*-
from distutils.core import setup, Extension
# define the extension module
uinput_wrapping_module = Extension('uinput_wrapping_module', sources=['uinput_wrapping_module.c','write_keyboard.c','timed_keystrokes.c'])
# run the setup
setup(ext_modules=[uinput_wrapping_module],
    name='Uinput wrapping module',
    version='2.0',
    description='Wrapped C to call uinput methods from python',
    long_description='This python module is used to call C methods, that are meant to send keyboard inputs generated by an uinput device.'
    + 'This module takes place in NINA project that intended to program a small IA that browses on the web to dizzy addtrackers.',
    author='Etienne JODRY',
    author_email='etienne.jodry@hotmail.fr',
    url='https://github.com/Varpie/ProjetNINA',
    license='GNU/GPLv3'
    )
